### ISSUE TITLE
Researches about Network Pruning & Architecture

### ISSUE THREAD

**Issue by simcity429** [ciplab/2019-winter-reading-project#9]
[Network Architecture.pptx](https://github.com/ciplab/2019-winter-reading-project/files/4085101/Network.Architecture.pptx)

**Comment by kingsj0405** [comment]
### Lottery Ticket Hypothesis

- Frankle&Carbin2019, Hattie2019
- Dense, Randomly-initliazed Network 안에 Lottery Ticket(더 작은 서브네트워크)가 있다
- Pruning한 뒤에 맨 처음 initialized value를 가져다 붙인다
- network architecture와 initialized weight는 튜플이다!
- (+) continual training: 성능은 별로였다
- LT weights move larger than pruned weights
- Zhou2019
- weight mask, pruning strategy를 바꿔보았다
- Mask 1 Action --> Only Sign matters
- Q. value large or small?
- Mask 0 Action --> masking as training
- Supermask: update only mask
- `g(m) = Bern(Sigmoid(m))`, `Bern`은 re-parametric으로 미분가능하다
- Lottery의 일종이다!

### Algorithm to find LT Network

- Vivek2019
- Supermask의 단점은 stochastic하다는 것이다
- `s`는 masking score

![image](https://user-images.githubusercontent.com/13496612/72771663-fab79780-3c44-11ea-8ecd-a7bcf7ef3fe2.png)

- 미분된 값을 음수, Z를 양수라고 가정하고 해본 뒤, 거꾸로도 해본다!
- 결국 모든 경우에 Loss가 줄어들면 `I_v`가 늘어나기를 원하게된다
- score를 높인다!

### Weight Agnostic Neural Network

- Adam&Ha2019
- Network Architecture에만 집중을 해보자!
- Weight Agnostic(weight-invariant한) Network를 찾아보기
- [Demo](https://weightagnostic.github.io/)

**Comment by tldtldcpfl** [comment]
[ Lottery Ticket Hypothesis ]
- Frankle&Carbin2019, Hattie2019

- 가설 : Dense, randomly initialzed network안에 good SubNetwork (Winning ticket))
             가 있다.  
            
![image](https://user-images.githubusercontent.com/25386336/72782129-58101080-3c66-11ea-83e0-de29fde6ced8.png)

- How to find wining ticket ?  
   -> Iterative Pruning
         - Strategy1 : Iterative pruning with resetting.
         - Strategy2 : Iterative pruning continued training 

- Experiment Details
 
 1. [ edge 끊어내기 ]  weight절댓값보다 일정 threshold보다 작은 애들은 없앰(pruning)
   
 2. [ 저장해놓은 initialzed값 붙이기 ] -> 새로운 subnetwork 생성  ** 남은 subnetwork  - 저장해놓은**  가중치를 갖다 붙이기 
     
 3. 맨 처음 initialized된 값들과의  연관성있음 

 4. [결과값] 유일하게 처음 가중치 복귀 후 트레이닝을 한 값이 가장 좋았다 

  - 실험값 그래프 -  x축: innit y: weight train 색깔 - 살아남은 subnetwork  
     
  -  mask1 action - 살아남은 애들 끼리만 suffle (값만 바꿈) , constant
   

  ** 밝혀 낸 사실 : 처음 initialized된 값과 비슷하게하면 거의 성공함

      + - 부호만 맞춘게 잘 작동했음 lottery보다 잘됌 

      살린 거에 대해서 첫값 갖고올때 +,- 만 잘됨 0.5
      첫값의 값이 중요한게 아니라 부호가 중요했다

   ** [mask 0 action ]   왜 0로 여야만 하나! - > 증명하려고 가설을 세움 : 

      0에 수렴하다가 잘린 애들도 있을 것임 - >  threshold 넘은 애들도 프루닝 

    - This paper said that their proposed method is a mask as training 
        => training의 새로운 관점 제시 [uber 논문]
-------------------
 [supermask]

 - mask - 0/1 살릴지 죽일지 binary하게 결정함
 
 -  어떻게 supermask를 찾을까? - 방법 제시 - 이진을 backpro로 훈련 
       -> continual value 
  ---------------------------------------------------------------------
[ Algorithm to find LT Network - New way to get Supermask! ] 
  이제는 randomly initialized vale만 씀
  wieght를 건들지 않고 pruning만 건듦



  베루누이 샘플링 - 미분가능 ** 중요

   wi는 절대 건들지 않음
 
   random한 value를 가지고도 성능을 개선시킬 수 있다는 거지 95.3% MNIS

   random한 값들로만 training 

   
  
  
  [오컴의 면도날 ]  - 불필요한 거는 제시하지말 것


->  weight는 적을수록 좋다 - >  얼만큼 적을 것인가?

->  결국엔 optimization    


  [vivek lt algo]

  - weight는 건들지 않음 

  - u 퍼셉트론에서 나오는  z

  - iv 증가 -> loss 증가 

   - 스코어가 결국 늘어나게됨 -> 스코어가 높을수록 참여할 수 있음
